"""
Telemetry Configuration for Signal Generator

Sets up Prometheus metrics and process resource monitoring.
Uses native prometheus_client for reliable cross-platform metrics export.
"""
import logging
from typing import Optional
import psutil
import threading
import time

from prometheus_client import start_http_server, Gauge, Counter, Histogram, REGISTRY
import os

logger = logging.getLogger(__name__)


# ── Process resource metrics ──────────────────────────────────────────────

process_cpu_percent = Gauge(
    'process_cpu_percent',
    'CPU usage percentage of this process',
    ['service']
)

process_memory_bytes = Gauge(
    'process_memory_bytes',
    'Memory usage in bytes of this process',
    ['service', 'type']
)

process_threads = Gauge(
    'process_threads',
    'Number of threads in this process',
    ['service']
)

process_open_files = Gauge(
    'process_open_files',
    'Number of open file descriptors',
    ['service']
)


# ── Signal generation metrics ─────────────────────────────────────────────

signals_generated_total = Counter(
    'signals_generated_total',
    'Total signals generated by generator and signal type',
    ['signal_type', 'source', 'generator']
)

signal_generation_duration_seconds = Histogram(
    'signal_generation_duration_seconds',
    'Time taken to generate signals by generator',
    ['generator']
)

generator_scans_total = Counter(
    'generator_scans_total',
    'Total number of scans per generator',
    ['generator']
)

generator_scan_errors_total = Counter(
    'generator_scan_errors_total',
    'Total scan errors per generator',
    ['generator']
)


# ── Kafka metrics ─────────────────────────────────────────────────────────

kafka_publish_duration_seconds = Histogram(
    'kafka_publish_duration_seconds',
    'Time taken to publish signal to Kafka',
    ['signal_type']
)

kafka_publish_success_total = Counter(
    'kafka_publish_success_total',
    'Total successful Kafka publishes by signal type',
    ['signal_type']
)

kafka_publish_failure_total = Counter(
    'kafka_publish_failure_total',
    'Total failed Kafka publishes by signal type',
    ['signal_type', 'error_type']
)


# ── Finnhub API metrics ──────────────────────────────────────────────────

finnhub_api_calls_total = Counter(
    'finnhub_api_calls_total',
    'Total Finnhub API calls by indicator type',
    ['indicator']
)

finnhub_api_errors_total = Counter(
    'finnhub_api_errors_total',
    'Total Finnhub API errors by error type',
    ['error_type']
)


class MetricsCollector:
    """Wrapper that provides the same interface as the OTel meter-based metrics."""

    def __init__(self):
        self.signals_generated = _CounterAdapter(signals_generated_total)
        self.signal_generation_duration = _HistogramAdapter(signal_generation_duration_seconds)
        self.generator_scans_total = _CounterAdapter(generator_scans_total)
        self.generator_scan_errors = _CounterAdapter(generator_scan_errors_total)
        self.kafka_publish_duration = _HistogramAdapter(kafka_publish_duration_seconds)
        self.kafka_publish_success = _CounterAdapter(kafka_publish_success_total)
        self.kafka_publish_failure = _CounterAdapter(kafka_publish_failure_total)
        self.finnhub_api_calls = _CounterAdapter(finnhub_api_calls_total)
        self.finnhub_api_errors = _CounterAdapter(finnhub_api_errors_total)


class _CounterAdapter:
    """Adapts prometheus_client Counter to OTel-like .add(amount, attributes) interface."""

    def __init__(self, counter: Counter):
        self._counter = counter

    def add(self, amount, attributes=None):
        if attributes:
            self._counter.labels(**attributes).inc(amount)
        else:
            self._counter.inc(amount)


class _HistogramAdapter:
    """Adapts prometheus_client Histogram to OTel-like .record(value, attributes) interface."""

    def __init__(self, histogram: Histogram):
        self._histogram = histogram

    def record(self, value, attributes=None):
        if attributes:
            self._histogram.labels(**attributes).observe(value)
        else:
            self._histogram.observe(value)


def setup_telemetry(
    service_name: str = "signal-generator",
    service_version: str = "1.0.0",
    metrics_port: int = 8001
) -> MetricsCollector:
    """
    Set up Prometheus metrics for the signal generator.

    Returns:
        MetricsCollector with counters/histograms matching the OTel interface.
    """
    # Start Prometheus metrics HTTP server
    try:
        start_http_server(port=metrics_port)
        logger.info(f"Prometheus metrics endpoint started on port {metrics_port}")
    except OSError as e:
        logger.warning(f"Failed to start metrics server on port {metrics_port}: {e}")

    # Start process metrics collection thread
    start_process_metrics_collection(service_name)

    logger.info(f"Telemetry setup complete for {service_name}")

    return MetricsCollector()


def start_process_metrics_collection(service_name: str, interval: int = 15):
    """Start background thread to collect process resource metrics."""
    process = psutil.Process()

    def collect_metrics():
        while True:
            try:
                cpu_percent = process.cpu_percent(interval=1)
                process_cpu_percent.labels(service=service_name).set(cpu_percent)

                mem_info = process.memory_info()
                process_memory_bytes.labels(service=service_name, type='rss').set(mem_info.rss)
                process_memory_bytes.labels(service=service_name, type='vms').set(mem_info.vms)

                num_threads = process.num_threads()
                process_threads.labels(service=service_name).set(num_threads)

                try:
                    num_fds = len(process.open_files())
                    process_open_files.labels(service=service_name).set(num_fds)
                except (psutil.AccessDenied, AttributeError):
                    pass
            except Exception as e:
                logger.error(f"Error collecting process metrics: {e}")

            time.sleep(interval)

    metrics_thread = threading.Thread(target=collect_metrics, daemon=True)
    metrics_thread.start()
    logger.info(f"Process metrics collection started for {service_name}")


def get_meter() -> MetricsCollector:
    """Get a new MetricsCollector instance."""
    return MetricsCollector()
