"""add_skipped_execution_status

Revision ID: 655ec350a488
Revises: f06dbda05951
Create Date: 2025-10-28 21:10:53.380794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655ec350a488'
down_revision = 'f06dbda05951'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

