"""Add version column for optimistic locking

Revision ID: ffddd94fe476
Revises: 20260207_float_interval
Create Date: 2026-02-07 21:42:41.673944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffddd94fe476'
down_revision = '20260207_float_interval'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add version column as nullable first, then set default and make not null
    op.add_column('executions', sa.Column('version', sa.Integer(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE executions SET version = 1 WHERE version IS NULL")
    # Now make it not null with server default
    op.alter_column('executions', 'version',
               existing_type=sa.Integer(),
               nullable=False,
               server_default='1')
    
    op.alter_column('executions', 'mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('executions', 'execution_phase',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('executions', 'monitor_interval_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_models', 'model_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_llm_models_is_active'), table_name='llm_models')
    op.drop_index(op.f('idx_llm_models_model_id'), table_name='llm_models')
    op.alter_column('pipelines', 'trigger_mode',
               existing_type=postgresql.ENUM('signal', 'periodic', name='triggermode'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scanners', 'scanner_type',
               existing_type=postgresql.ENUM('manual', 'filter', 'api', name='scannertype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scanners', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_scanners_id'), table_name='scanners')
    op.drop_constraint(op.f('scanners_user_id_fkey'), 'scanners', type_='foreignkey')
    op.create_foreign_key(None, 'scanners', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'subscription_tier',
               existing_type=postgresql.ENUM('free', 'basic', 'pro', 'enterprise', name='subscriptiontier'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'max_active_pipelines',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'max_active_pipelines',
               existing_type=sa.INTEGER(),
               server_default=sa.text('2'),
               existing_nullable=False)
    op.alter_column('users', 'subscription_tier',
               existing_type=postgresql.ENUM('free', 'basic', 'pro', 'enterprise', name='subscriptiontier'),
               server_default=sa.text("'free'::subscriptiontier"),
               existing_nullable=False)
    op.drop_constraint(None, 'scanners', type_='foreignkey')
    op.create_foreign_key(op.f('scanners_user_id_fkey'), 'scanners', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_scanners_id'), 'scanners', ['id'], unique=False)
    op.alter_column('scanners', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('scanners', 'scanner_type',
               existing_type=postgresql.ENUM('manual', 'filter', 'api', name='scannertype'),
               server_default=sa.text("'manual'::scannertype"),
               existing_nullable=False)
    op.alter_column('pipelines', 'trigger_mode',
               existing_type=postgresql.ENUM('signal', 'periodic', name='triggermode'),
               server_default=sa.text("'periodic'::triggermode"),
               existing_nullable=False)
    op.create_index(op.f('idx_llm_models_model_id'), 'llm_models', ['model_id'], unique=False)
    op.create_index(op.f('idx_llm_models_is_active'), 'llm_models', ['is_active'], unique=False)
    op.alter_column('llm_models', 'model_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('executions', 'monitor_interval_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('executions', 'execution_phase',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'execute'::character varying"),
               existing_nullable=False)
    op.alter_column('executions', 'mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'paper'::character varying"),
               existing_nullable=False)
    op.drop_column('executions', 'version')
    # ### end Alembic commands ###

