"""
Trade Review Agent — Senior trader quality gate before execution

This agent synthesizes the outputs of BiasAgent, StrategyAgent, and RiskManagerAgent
into a final APPROVE / REJECT decision using a senior Wall Street trader persona.
It does not call any tools — it reads the existing pipeline state and reasons about it.
"""
import json
import re
import structlog
from typing import Dict, Any, Optional

from app.agents.base import BaseAgent, AgentProcessingError
from app.agents.prompts import load_prompt
from app.schemas.pipeline_state import (
    PipelineState,
    AgentMetadata,
    AgentConfigSchema,
    TradeReview,
)
from app.services.llm_provider import create_openai_client, resolve_chat_model
from app.config import settings

logger = structlog.get_logger()


class TradeReviewAgent(BaseAgent):
    """
    Senior Trader Review Agent — final quality gate before trade execution.

    Reads bias, strategy, and risk assessment from PipelineState and makes
    a holistic APPROVE / REJECT / HOLD decision using the Marcus Chen persona.
    Always runs before TradeManagerAgent. No tools needed.
    """

    @classmethod
    def get_metadata(cls) -> AgentMetadata:
        from app.services.model_registry import model_registry
        from app.database import SessionLocal

        db = SessionLocal()
        try:
            model_choices = model_registry.get_model_choices_for_schema(db)
        finally:
            db.close()

        return AgentMetadata(
            agent_type="trade_review_agent",
            name="Senior Trader Review",
            description=(
                "Senior Wall Street trader persona that reviews the full trade setup "
                "(bias + strategy + risk) and makes the final APPROVE / REJECT decision. "
                "Quality gate before any capital is committed."
            ),
            category="analysis",
            version="1.0.0",
            icon="gavel",
            pricing_rate=0.08,
            is_free=False,
            requires_timeframes=[],
            requires_market_data=True,
            requires_position=False,
            default_tools=[],  # No tools — pure state synthesis
            supported_tools=[],
            config_schema=AgentConfigSchema(
                type="object",
                title="Senior Trader Review Configuration",
                properties={
                    "min_bias_confidence": {
                        "type": "number",
                        "title": "Minimum Bias Confidence",
                        "description": "Reject if bias confidence is below this AND strategy confidence is also below min_strategy_confidence",
                        "default": 0.6,
                    },
                    "min_strategy_confidence": {
                        "type": "number",
                        "title": "Minimum Strategy Confidence",
                        "description": "Reject if strategy confidence is below this AND bias confidence is also below min_bias_confidence",
                        "default": 0.65,
                    },
                    "min_risk_reward": {
                        "type": "number",
                        "title": "Minimum Risk/Reward Ratio",
                        "description": "Always reject if R/R falls below this threshold",
                        "default": 1.5,
                    },
                    "model": {
                        "type": "string",
                        "title": "AI Model",
                        "description": "LLM model for trade review",
                        "enum": model_choices,
                        "default": "gpt-4o" if "gpt-4o" in model_choices else (model_choices[0] if model_choices else "gpt-4o"),
                    },
                },
                required=[],
            ),
            can_initiate_trades=False,
            can_close_positions=False,
        )

    def process(self, state: PipelineState) -> PipelineState:
        """
        Review the full trade setup and set state.trade_review.

        Gracefully handles missing upstream data — HOLD if no strategy,
        REJECTED if hard rules are violated, otherwise defers to LLM.
        """
        from app.services.langfuse_service import trace_agent_execution

        self.log(state, "🎩 Senior trader review in progress")

        trace = trace_agent_execution(
            execution_id=str(state.execution_id),
            agent_type=self.metadata.agent_type,
            agent_id=self.agent_id,
            pipeline_id=str(state.pipeline_id),
            user_id=str(state.user_id),
        )

        # --- No strategy: nothing to review ---
        if not state.strategy:
            state.trade_review = TradeReview(
                decision="HOLD",
                confidence=1.0,
                reasoning="No strategy was generated by the pipeline — nothing to review.",
                key_concerns=["Strategy agent returned no result"],
                key_strengths=[],
            )
            self.log(state, "No strategy available — review decision: HOLD")
            self._record(state, state.trade_review)
            return state

        strategy = state.strategy

        # --- HOLD signal: passthrough ---
        if strategy.action == "HOLD":
            state.trade_review = TradeReview(
                decision="HOLD",
                confidence=1.0,
                reasoning="Strategy agent returned a HOLD signal. No trade to review.",
                key_concerns=[],
                key_strengths=[],
            )
            self.log(state, "Strategy is HOLD — review decision: HOLD")
            self._record(state, state.trade_review)
            return state

        # --- Pre-flight hard rules (no LLM needed) ---
        hard_reject = self._check_hard_rules(state)
        if hard_reject:
            state.trade_review = hard_reject
            self.log(state, f"Hard rule rejection: {hard_reject.reasoning}")
            self._record(state, state.trade_review)
            return state

        # --- LLM synthesis ---
        try:
            review = self._llm_review(state)
            state.trade_review = review
            self.log(state, f"Trade review decision: {review.decision} (confidence={review.confidence:.2f})")
        except Exception as e:
            logger.error("trade_review_llm_failed", error=str(e))
            # Fail-safe for live trading: block the trade on review failure.
            # For paper/simulation mode we fail-open to avoid blocking research workflows.
            is_live = state.mode == "live"
            fallback_decision = "REJECTED" if is_live else "APPROVED"
            fallback_note = (
                "Trade REJECTED because automated review failed in live mode. "
                "Manual review required before executing."
                if is_live else
                "Trade review LLM failed in paper mode. Defaulting to APPROVED for research continuity."
            )
            state.trade_review = TradeReview(
                decision=fallback_decision,
                confidence=0.0 if is_live else 0.5,
                reasoning=f"Trade review LLM failed ({str(e)[:80]}). {fallback_note}",
                key_concerns=["Review agent encountered an error — manual oversight required"],
                key_strengths=[],
                trader_notes=fallback_note,
            )
            self.add_warning(state, f"Trade review LLM failed: {str(e)}")

        self._record(state, state.trade_review)
        return state

    # -------------------------------------------------------------------------
    # Internal helpers
    # -------------------------------------------------------------------------

    def _check_hard_rules(self, state: PipelineState) -> Optional[TradeReview]:
        """
        Apply hard mechanical rules before calling the LLM.
        Returns a TradeReview rejection if any rule fires, else None.
        """
        strategy = state.strategy
        risk = state.risk_assessment
        bias = self._primary_bias(state)

        min_rr = float(self.config.get("min_risk_reward", 1.5))
        min_bias_conf = float(self.config.get("min_bias_confidence", 0.6))
        min_strat_conf = float(self.config.get("min_strategy_confidence", 0.65))

        # Rule 1: Direction conflict
        if bias:
            bias_dir = bias.bias  # "BULLISH" or "BEARISH"
            action = strategy.action  # "BUY" or "SELL"
            conflict = (bias_dir == "BULLISH" and action == "SELL") or \
                       (bias_dir == "BEARISH" and action == "BUY")
            if conflict:
                return TradeReview(
                    decision="REJECTED",
                    confidence=0.95,
                    reasoning=(
                        f"Direction conflict: bias is {bias_dir} but strategy proposes a {action}. "
                        "Entering against the established bias is a high-risk, low-probability trade."
                    ),
                    key_concerns=[f"Bias={bias_dir} contradicts strategy action={action}"],
                    key_strengths=[],
                )

        # Rule 2: Dual low confidence
        bias_conf = bias.confidence if bias else 0.0
        strat_conf = strategy.confidence if strategy.confidence else 0.0
        if bias_conf < min_bias_conf and strat_conf < min_strat_conf:
            return TradeReview(
                decision="REJECTED",
                confidence=0.85,
                reasoning=(
                    f"Both bias confidence ({bias_conf:.2f}) and strategy confidence ({strat_conf:.2f}) "
                    f"are below required thresholds ({min_bias_conf}/{min_strat_conf}). "
                    "No clear edge present."
                ),
                key_concerns=[
                    f"Bias confidence {bias_conf:.2f} < {min_bias_conf}",
                    f"Strategy confidence {strat_conf:.2f} < {min_strat_conf}",
                ],
                key_strengths=[],
            )

        # Rule 3: Insufficient R/R
        if risk and risk.risk_reward_ratio > 0 and risk.risk_reward_ratio < min_rr:
            return TradeReview(
                decision="REJECTED",
                confidence=0.9,
                reasoning=(
                    f"Risk/reward ratio of {risk.risk_reward_ratio:.2f}:1 is below the minimum "
                    f"threshold of {min_rr}:1. This trade does not justify the capital at risk."
                ),
                key_concerns=[f"R/R {risk.risk_reward_ratio:.2f}:1 < minimum {min_rr}:1"],
                key_strengths=[],
            )

        return None

    def _llm_review(self, state: PipelineState) -> TradeReview:
        """Call the LLM to make the final review decision."""
        client = create_openai_client()
        model_id = resolve_chat_model(self.config.get("model", settings.OPENAI_MODEL))

        system_prompt = load_prompt("trade_review_agent_system")
        trade_brief = self._build_trade_brief(state)

        response = client.chat.completions.create(
            model=model_id,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": trade_brief},
            ],
            temperature=0.2,
            timeout=30,
        )

        raw = response.choices[0].message.content.strip()
        return self._parse_review(raw)

    def _build_trade_brief(self, state: PipelineState) -> str:
        """Assemble the structured trade brief from pipeline state."""
        strategy = state.strategy
        risk = state.risk_assessment
        bias = self._primary_bias(state)

        lines = [
            "=== TRADE BRIEF FOR REVIEW ===",
            f"Symbol: {state.symbol}",
            "",
        ]

        # Bias section
        if bias:
            lines += [
                "--- MARKET BIAS ---",
                f"Direction: {bias.bias}",
                f"Confidence: {bias.confidence:.2f}",
                f"Timeframe: {bias.timeframe}",
                f"Reasoning: {bias.reasoning[:200]}",
            ]
            if bias.key_factors:
                lines.append(f"Key factors: {', '.join(bias.key_factors[:4])}")
        else:
            lines += ["--- MARKET BIAS ---", "No bias data available"]

        lines.append("")

        # Strategy section
        lines += [
            "--- TRADE STRATEGY ---",
            f"Action: {strategy.action}",
            f"Confidence: {strategy.confidence:.2f}",
            f"Entry: {strategy.entry_price}",
            f"Stop Loss: {strategy.stop_loss}",
            f"Take Profit: {strategy.take_profit}",
            f"Pattern: {strategy.pattern_detected or 'Not specified'}",
            f"Reasoning: {strategy.reasoning[:200]}",
        ]

        lines.append("")

        # Risk section
        if risk:
            lines += [
                "--- RISK ASSESSMENT ---",
                f"Approved by risk manager: {risk.approved}",
                f"Position size: {risk.position_size}",
                f"Risk/Reward: {risk.risk_reward_ratio:.2f}:1",
                f"Max loss: ${risk.max_loss_amount:.2f}",
            ]
            if risk.warnings:
                lines.append(f"Warnings: {'; '.join(risk.warnings)}")
            lines.append(f"Reasoning: {risk.reasoning[:150]}")
        else:
            lines += ["--- RISK ASSESSMENT ---", "No risk data available"]

        return "\n".join(lines)

    def _parse_review(self, raw: str) -> TradeReview:
        """Parse JSON response from LLM into TradeReview."""
        # Strip markdown fences if present
        cleaned = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()

        try:
            data = json.loads(cleaned)
        except json.JSONDecodeError:
            # Try to extract JSON block
            match = re.search(r"\{.*\}", cleaned, re.DOTALL)
            if match:
                data = json.loads(match.group())
            else:
                raise AgentProcessingError(f"Could not parse trade review JSON: {cleaned[:200]}")

        decision = str(data.get("decision", "HOLD")).upper()
        if decision not in ("APPROVED", "REJECTED", "HOLD"):
            # Unknown decision — default to HOLD (neutral) rather than APPROVED
            decision = "HOLD"

        return TradeReview(
            decision=decision,
            confidence=float(data.get("confidence", 0.7)),
            reasoning=str(data.get("reasoning", "")),
            key_concerns=list(data.get("key_concerns", [])),
            key_strengths=list(data.get("key_strengths", [])),
            trader_notes=data.get("trader_notes"),
        )

    def _primary_bias(self, state: PipelineState):
        """Return the most relevant bias from state.biases (prefer shorter TF)."""
        if not state.biases:
            return None
        # Prefer 1h > 4h > 1d > whatever is first
        for tf in ("1h", "4h", "1d", "1D", "D"):
            if tf in state.biases:
                return state.biases[tf]
        return next(iter(state.biases.values()))

    def _record(self, state: PipelineState, review: TradeReview):
        """Write a structured report to the agent_reports dict."""
        status_map = {"APPROVED": "completed", "REJECTED": "warning", "HOLD": "skipped"}
        emoji_map = {"APPROVED": "✅", "REJECTED": "❌", "HOLD": "⏸️"}
        emoji = emoji_map.get(review.decision, "")

        metrics = {
            "Decision": f"{emoji} {review.decision}",
            "Confidence": f"{review.confidence:.0%}",
        }
        if state.risk_assessment:
            metrics["R/R Ratio"] = f"{state.risk_assessment.risk_reward_ratio:.2f}:1"

        self.record_report(
            state,
            title=f"Senior Trader Review — {review.decision}",
            summary=review.reasoning,
            status=status_map.get(review.decision, "completed"),
            details=review.trader_notes,
            metrics=metrics,
            data={
                "decision": review.decision,
                "confidence": review.confidence,
                "key_concerns": review.key_concerns,
                "key_strengths": review.key_strengths,
            },
        )
