name: KuberTrading
options:
  bundleIdPrefix: com.kubertrading
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  KuberTrading:
    type: application
    platform: iOS
    sources:
      - path: KuberTrading
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kubertrading.app
        INFOPLIST_GENERATION_MODE: GeneratedByBuildSystem
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSFaceIDUsageDescription: "Use Face ID for quick and secure login"
        INFOPLIST_KEY_CFBundleDisplayName: "KuberTrading"
        CODE_SIGN_ENTITLEMENTS: KuberTrading/KuberTrading.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: true
    entitlements:
      path: KuberTrading/KuberTrading.entitlements
      properties:
        aps-environment: development
        com.apple.developer.associated-domains:
          - "applinks:app.kubertrading.com"
